### ISSUE TITLE
Extremely slow training compared to EfficientNet

### ISSUE THREAD

**Issue by CaptainDario** [sebastian-sz/efficientnet-lite-keras#11] opened 2021-06-21 18:30 UTC
This repo is working well for me, thanks!
However the training time is very high.
Training on my dataset for one epoch takes 20min for EfficientNet and around 1.30h for EfficientNet Lite.
Is this normal or am I doing something wrong?

```
from efficientnet_lite import EfficientNetLiteB0

eff_net_lite = EfficientNetLiteB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=len(ls),
    pooling="max",
    classifier_activation="softmax"
)

hist = eff_net_lite.fit(
    train,
    validation_data=val,
    epochs=25,
    initial_epoch=0,
    workers=16,
    use_multiprocessing=True,
    callbacks=callbacks_list
)
```

**Comment by suraj-maniyar** [comment] 2021-06-21 19:50
I am seeing similar behavior.
Training time for EfficientNet-Lite B3 was ~77 hours. I had to lower the batch size to 16 to get feasible training time.
It would be nice to know if there is a fix for allowing larger batch sizes without increasing per-epoch time.
Thanks.

**Comment by CaptainDario** [comment] 2021-06-21 20:06
I just figured out that windows update messed up my cuda installation.
Training was slow because I was running without GPU acceleration...

@suraj-maniyar did you try EfficientNet-3 and had faster training times?
And for how many epochs did you train?

**Comment by sebastian-sz** [comment] 2021-06-22 07:15
These training times are extreme. Definitely should not be like this. I will look into this in the nearest occasion.

**Comment by sebastian-sz** [comment] 2021-06-22 08:50
@CaptainDario

Hi, how did you pass the one-channel input shape to both models? You wrote:
```python
eff_net_lite = EfficientNetLiteB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=len(ls),
    pooling="max",
    classifier_activation="softmax"
)
```
However, I'm getting 
```python
ValueError: The input must have 3 channels; got `input_shape=(64, 64, 1)`
```
for both lite, and non-lite versions.

**Comment by CaptainDario** [comment] 2021-06-22 09:00
@sebastian-sz I load 64x64 grayscale images from disk.
Here is the whole model definition.

``` python
from tensorflow.keras.layers.experimental.preprocessing import Resizing, Rescaling, RandomZoom, RandomRotation, RandomTranslation

# preprocessing layer
img_augmentation = tf.keras.Sequential(
    [
        # resize images and rescale values
        Resizing(64, 64, "lanczos3"),
        Rescaling(scale=1.0/255),

        # random data augmentation
        RandomZoom(height_factor=(0.0, 1.0), width_factor=(0.0, 1.0), 
            fill_mode='constant', interpolation='bilinear', fill_value=0.0
        ),
        RandomTranslation(0.2, 0.2, fill_mode="constant"),
        RandomRotation(0.1, fill_mode='constant', interpolation='bilinear'),
        
    ],
    name = "img_augmentation"
)

# efficientnet lite
from efficientnet_lite import EfficientNetLiteB0

eff_net_lite = EfficientNetLiteB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=len(ls),
    pooling="max",
    classifier_activation="softmax"
)

# join models
inputs = tf.keras.layers.Input(shape=(64, 64, 1))
x = img_augmentation(inputs)
outputs = eff_net_lite(x)

f16_model = tf.keras.Model(inputs, outputs, name="EfficientNet")

#path where the model should be saved
model_dir = os.path.join(os.getcwd(), "model")
print("model_dir:", model_dir)

#optimizer and loss
l_r = 0.001
opt = tf.keras.optimizers.Adam(learning_rate=l_r)

METRICS = [
    'accuracy', 
    tf.keras.metrics.Precision(name='precision'),
    tf.keras.metrics.Recall(name='recall'),
]

f16_model.compile(optimizer=opt, loss="categorical_crossentropy", metrics=METRICS)

# leraning rate scheduler
def scheduler(epoch, lr):
    return l_r - ((l_r / 100 * 4) * (epoch // 3))

scheduler_callback = tf.keras.callbacks.LearningRateScheduler(scheduler, verbose=1)
callbacks_list = [scheduler_callback]

from tensorflow.keras.callbacks import ModelCheckpoint

#checkpoint setup
filepath = os.path.join(model_dir, "tf", "checkpoints", "weights-improvement-{epoch:02d}-{val_accuracy:.2f}.hdf5")
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')

callbacks_list.append(checkpoint)

print("checkpoints dir:", filepath)

# train the model
#train the model
hist = f16_model.fit(
    train,
    validation_data=val,
    epochs=25,
    initial_epoch=0,
    workers=16,
    use_multiprocessing=True,
    callbacks=callbacks_list
)
```

I have a jupyter notebook setup you can take a look [here](https://github.com/CaptainDario/DaKanji-ML/blob/feature-recognize_more_characters/single_kanji_cnn/single_kanji_cnn_training.ipynb). However it may not work completely (I am currently retraining the network).

**Comment by CaptainDario** [comment] 2021-06-22 09:03
After reinstalling CUDA my training times are already much better. However still around 2x slower than EfficientNet.
But I am using mixed_precision for EfficientNet Lite (awesome that this is possible without the SE and swish!). However this should if at all lead to faster training.

**Comment by sebastian-sz** [comment] 2021-06-22 09:53
@CaptainDario 
I'm having hard time reproducing the issue. I managed to pass your input shape (it works with `weights=None` instead of `weights="imagenet"`).

For a simple flower dataset I'm getting the following results (Tesla T4):

1. EfficientNetB0 FP32:
```python
Epoch 1/4
92/92 [==============================] - 53s 111ms/step
Epoch 2/4
92/92 [==============================] - 8s 89ms/step
Epoch 3/4
92/92 [==============================] - 9s 90ms/step
Epoch 4/4
92/92 [==============================] - 8s 85ms/step
```

2. EfficientNetLiteB0 FP32:
```python
Epoch 1/4
92/92 [==============================] - 13s 68ms/step 
Epoch 2/4
92/92 [==============================] - 6s 61ms/step
Epoch 3/4
92/92 [==============================] - 6s 60ms/step
Epoch 4/4
92/92 [==============================] - 6s 60ms/step
```

3. EfficientNetLiteB0 FP16 (not much change here):
```python
Epoch 1/4
92/92 [==============================] - 15s 68ms/step
Epoch 2/4
92/92 [==============================] - 6s 60ms/step
Epoch 3/4
92/92 [==============================] - 6s 60ms/step
Epoch 4/4
92/92 [==============================] - 6s 61ms/step
```

4. EfficientNetB0 FP16:
Doesn't work with mixed precision in TF 2.5.

You can find my benchmark notebook [at this link](https://colab.research.google.com/drive/1r7ge049dP4xmIEMxCIVWk3X_F1TXMwJZ?usp=sharing).

The training times seem to be similar in the above notebook (and as expected, slightly lower for Lite variant). I don't know why you observe such performance drop. I'm still analysing your code for potential reasons why the lite models are so slow. 

Are the training times comparable? Are you using the same data, the same callbacks, the same augmentations for both models?

If you have more information, please let me know!

**Comment by CaptainDario** [comment] 2021-06-22 11:08
Thank you for taking a look!
I am not sure what the problem could be. However chances are high that the problem is related to my setup. I will start training EfficientNet again an look at the training times.
I will than update here.

**Comment by sebastian-sz** [comment] 2021-06-22 15:09
@suraj-maniyar Hi, could you also provide some examples of scenarios with bad performance?

**Comment by CaptainDario** [comment] 2021-06-22 19:04
@sebastian-sz thank you very much for your effort.
However this seems to be related to some issues regarding my setup.
I just retrained with EfficientNet and the time also went drastically up...

Sorry for taking you so much time. From my point of view this can now be closed.

**Comment by CaptainDario** [comment] 2021-06-22 19:05
And thank you again for this wonderful repo!

**Comment by sebastian-sz** [comment] 2021-06-24 07:41
@CaptainDario Thank you for the kind words!

Can you try to train your model (with your notebook) maybe on a smaller subset of data in Google Colab, so we can check if the performance is also bad there?

**Comment by CaptainDario** [comment] 2021-06-24 09:29
> Can you try to train your model (with your notebook) maybe on a smaller subset of data in Google Colab, so we can check if the performance is also bad there?

I can try to do that but my dataset is quite large (the produced cache files are ~120GB) and therefore I am not sure if it works on colab.

**Comment by sebastian-sz** [comment] 2021-06-24 09:35
@CaptainDario yes, 120 GB is too much for Colab. Can you try with a smaller subset? Maybe only take 100 images per class instead of all images?

**Comment by sebastian-sz** [comment] 2021-06-30 09:11
I'm closing this issue as it could not be reproduced in an isolated environment. It could be due to CUDA installation.

If you have other questions or are willing to further debug this with me, feel free to reopen!

**Closed by sebastian-sz** 2021-06-30 09:11 UTC

**Comment by CaptainDario** [comment] 2021-06-30 16:30
@sebastian-sz finally had the time to setup a notebook and run the training.
Sadly it was somehow connected to my setup and after a fresh setup it is training fast again.

Thank you for your time and sorry for the issue unrelated to your repo.
