### ISSUE TITLE
Supporting Quantization Aware Training (QAT)

### ISSUE THREAD

**Issue by ameyparanjape** [sebastian-sz/efficientnet-lite-keras#6] opened 2021-04-11 18:09 UTC
Thank you @sebastian-sz for resolving the relu issue. I can confirm that this new commit fixed the `ValueError: Unknown activation function:relu6`

I have a follow up on finetuning and creating efficient deployable model using `efficientnet-lite`. I want to train/finetune the model using Quantization Aware Training (QAT) utility in Tensorflow model optimization (tfmot) (like [this](https://sci.cafe/quantization-1)).

1) I tried using the `tfmot.quantization.keras.quantize_model` on the current lite model and I get the following error:
`ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.`

This makes sense since current version of quantization does not support recursive model. I was wondering if we can add a utility or a flag to support QAT while creating model?

2) I also tried to convert the model as a base_model, added a head on top of it and then creted a Keras model using `tf.keras.Model`, then I got following error:
`RuntimeError: Layer rescaling_1:<class 'tensorflow.python.keras.layers.preprocessing.image_preprocessing.Rescaling'> is not supported. You can quantize this layer by passing a 'tfmot.quantization.keras.QuantizeConfig' instance to the `quantize_annotate_layer` API.`

Is there any other way to iterate though the model and select and quantize the supported layers?

I saw a similar open issue on `tfmot` repo, but it seems stale. Any ideas will be appreciated, I'm also open to contribute, thank you!

**Comment by sebastian-sz** [comment] 2021-04-12 05:46
As far as I know the `tfmot` should work for this `efficientnet-lite` the same as for other Keras models. 

I will be looking into those two issues this week.

**Comment by ameyparanjape** [comment] 2021-04-12 14:30
To clarify my 2nd point, here is what I tried:
Code Snippet (you may need to import/install packages)
```python
def create_model(fine_tune=True):
    base_model=tf.keras.applications.EfficientNetB0(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
    
    base_model.trainable=fine_tune
    #QAT preparation
    base_model = tfmot.quantization.keras.quantize_model(base_model)

    x=tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
    x=tf.keras.layers.Dense(8, activation="relu")(x)
    x=tf.keras.layers.Dropout(0.2)(x)
    x=tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model=tf.keras.Model(inputs=base_model.input, outputs=x)

    return model

model=create_model(fine_tune=False)
```

This is to show that even if I use the default Keras model, it throws an error because some layer/s are not compatible with the `quantize_annotate_layer` API. So to get around that, my idea is to have a QAT flag while creating the model itself and handle it layer by layer, to take care of unsupported layers. Hope this clarifies what I am suggesting.

**Comment by sebastian-sz** [comment] 2021-04-13 08:03
@ameyparanjape thank you for providing a reproducible example. Upon closer lookup I don't think this is a problem with Keras, but a problem with Tensorflow Model Optimization Toolkit not supporting enough layers.

In case of EfficientNet, these layers are: `Rescaling`, `Normalization` and `Multiply` and even `Activation('swish')` - maybe more, but I did not check the rest.
In case of EfficientNet-lite, these layers are: `Normalization` (I didn't need `Rescaling` and `Multiply` exists only in SE blocks - they are not present in lite variant).

I have mixed feelings about the removal of preprocessing in lite variant, because now, the lite variant will expect the inputs in range -1, +1 and non-lite in range 0-255. This is risky and violates the rule of "least surprise" - someone might use lite variant with wrong inputs and get trash results.

In the future (depending if the official PR makes it through) I might make a larger refactor of this repository to support the options requested by you by default. At this moment, as I'm still awaing feedback from Tensorflow team, I can offer you a workaround:

### Quantize only part of the model
You can apply quantization to all the layers, except to those that produce errors -  [Tutorial link](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide#quantize_some_layers)
```python
# This will only work with lite backbone
lite_backbone = tf.keras.models.load_model("backbone_lite_notop.h5")

# Slightly modified make model fn:
def make_model(base_model, fine_tune=True):    
    base_model.trainable = fine_tune

    x=tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
    x=tf.keras.layers.Dense(8, activation="relu")(x)
    x=tf.keras.layers.Dropout(0.2)(x)
    x=tf.keras.layers.Dense(1, activation="sigmoid")(x)
    return tf.keras.Model(inputs=base_model.input, outputs=x)

model = make_model(lite_backbone)

def apply_quant_to_layers(layer):
    if isinstance(layer, tf.keras.layers.experimental.preprocessing.Normalization):
        return layer
    else:
        return tfmot.quantization.keras.quantize_annotate_layer(layer)

annotated_model = tf.keras.models.clone_model(
    model,
    clone_function=apply_quant_to_layers,
)

qm = tfmot.quantization.keras.quantize_apply(annotated_model)
qm.summary()
```
The above worked for me in Colab. Let me know if this helps you use TFMOT with lite model variants.

**Comment by ameyparanjape** [comment] 2021-04-14 05:01
@sebastian-sz Thank you for looking into this, and for an elaborate explanation.
I tried using your code snippet and here are my observations:
1) If I use the above code snippet as is (assuming "backbone_lite_notop.h5" are no-top weights for lite-0 model), I get this error - `ValueError: No model found in config file.`
at line - `lite_backbone = tf.keras.models.load_model("backbone_lite_notop.h5")`
2) If I use the above code snippet as is (assuming "backbone_lite_notop.h5" is a saved notop lite-0 model), I get this error - 
```
ValueError: Only some Keras activations under 'tf.keras.activations' are supported. For other activations, use 'Quantizer' directly, and update layer config using 'QuantizeConfig'.
```
On deeper look into this, it appears that this is raised while `quantize_annotate_layer()` on the last `dense` layer with `Sigmoid` activation. 
3) To work around this, I added a condition to not include the dense layer in `quantize_annotate_layer()`.
`if isinstance(layer, tf.keras.layers.experimental.preprocessing.Normalization) isinstance(layer,tf.keras.layers.Dense):`
instead of -
`if isinstance(layer, tf.keras.layers.experimental.preprocessing.Normalization)`

(I don't like this, but it works)

I'm puzzled about how it worked on your system. Am I missing anything?

**Comment by sebastian-sz** [comment] 2021-04-14 05:48
Yes, sorry I should clarify: `backbone_lite_notop.h5` is a keras saved model. Not only weights but entire model.

About the Issue with `tf.keras.activations` yes it looks like the last dense layer with `sigmoid` causes problems.

The snippet will still work if you modify your model function to separate Sigmoid from Dense:

```python
def make_model(base_model, fine_tune=True):    
    base_model.trainable = fine_tune

    x=tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
    x=tf.keras.layers.Dense(8, activation="relu")(x)
    x=tf.keras.layers.Dropout(0.2)(x)
    # Separate this:
    x=tf.keras.layers.Dense(1, activation="linear")(x)
    x=tf.keras.layers.Activation('sigmoid')(x)
    return tf.keras.Model(inputs=base_model.input, outputs=x)
```

This is weird and we should not have to do this. This could be an Issue with TFMOT.

**Comment by sebastian-sz** [comment] 2021-04-20 05:49
@ameyparanjape Hi, were you able to resolve the issue with the above solution?

**Comment by ameyparanjape** [comment] 2021-04-25 02:41
Hi @sebastian-sz , sorry about the delayed response, I was swamped with some other stuff past week. I think I will be able to give this a try in coming week. Thank you for following up!

**Comment by sebastian-sz** [comment] 2021-06-03 09:21
I largely refactored the repository to make it more accessible, easier to use. QAT should be supported now, so I'm closing this issue.

Feel free to reopen if you have any other questions!

**Closed by sebastian-sz** 2021-06-03 09:21 UTC
